NguyenTongPhucNguyen/Models/HomeModel.cs
using NguyenTongPhucNguyen.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NguyenTongPhucNguyen.Models
{
    public class HomeModel
    {
        public List<Category> ListCategories { get; set; }
        public List<Product> ListProducts { get; set; }
        public List<User> ListUsers { get; set; }
        public List<Brand> ListBrands { get; set; }
    }
}

NguyenTongPhucNguyen/Controllers/AllCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class AllCategoryController : Controller
    {
        // GET: AllCategory
        public ActionResult AllCategory()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Cart()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Category()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/HomeController.cs
using NguyenTongPhucNguyen.Context;
using NguyenTongPhucNguyen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class HomeController : Controller
    
    {
        WebBanHangEntities BanHang = new WebBanHangEntities();
        public ActionResult Index()
        {
            HomeModel model = new HomeModel();
            model.ListCategories = BanHang.Category.ToList();
            model.ListBrands = BanHang.Brand.ToList();
            model.ListUsers = BanHang.User.ToList();
            model.ListProducts = BanHang.Product.ToList();
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class ListController : Controller
    {
        // GET: List
        public ActionResult Index()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Detail()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenTongPhucNguyen.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Register()
        {
            return View();
        }
    }
}

NguyenTongPhucNguyen/Views/AllCategory/AllCategory.cshtml
@{
    ViewBag.Title = "AllCategory";
}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">

        <nav class="row">
            <div class="col-md-3">

                <div class="card card-category">
                    <div class="img-wrap" style="background: #ffd7d7">
                        <img src="~/Content/images/items/1.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Summer shirts</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Unisex T shirts</a></li>
                            <li><a href="">Casual shirts</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #FFF68D">
                        <img src="~/Content/images/items/2.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Winter jackets</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Leather jackets</a></li>
                            <li><a href="">Men's jackets</a></li>
                            <li><a href="">Heating battery clothes</a></li>
                            <li><a href="">Jeans jackets</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #bcffb8">
                        <img src="~/Content/images/items/3.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Shorts</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Jeans shorts</a></li>
                            <li><a href="">Swimming shorts</a></li>
                            <li><a href="">Another some shorts</a></li>
                            <li><a href="">Another category</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <div class="img-wrap" style="background: #c9fff3">
                        <img src="~/Content/images/items/4.jpg">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Travel bags </a></h4>
                        <ul class="list-menu">
                            <li><a href="">Leather bags</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #ddffeb">
                        <img src="~/Content/images/items/5.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Great items</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #dee4ff">
                        <img src="~/Content/images/items/6.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Kitchen furniture</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #ddffeb">
                        <img src="~/Content/images/items/2.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Great items</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Combi steamers</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
            <div class="col-md-3">
                <div class="card card-category">
                    <a href="#" class="img-wrap" style="background: #dee4ff">
                        <img src="~/Content/images/items/1.jpg">
                    </a>
                    <div class="card-body">
                        <h4 class="card-title"><a href="#">Other clothes</a></h4>
                        <ul class="list-menu">
                            <li><a href="">Jeans shorts</a></li>
                            <li><a href="">Cook & Hold ovens</a></li>
                            <li><a href="">Scherf Ice cream</a></li>
                            <li><a href="">Another category</a></li>
                            <li><a href="">Great items name</a></li>
                        </ul>
                    </div>
                </div>
            </div> <!-- col.// -->
        </nav> <!-- row.// -->


    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
<!-- ========================= SECTION SUBSCRIBE  ========================= -->
<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your inbox</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Your Email" type="email">
                    </div> <!-- col.// -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Subscribe </button>
                    </div> <!-- col.// -->
                </form>
                <small class="form-text">We’ll never share your email address with a third-party. </small>
            </div> <!-- col-md-6.// -->
        </div>


    </div>
</section>
<!-- ========================= SECTION SUBSCRIBE END// ========================= -->

NguyenTongPhucNguyen/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NguyenTongPhucNguyen/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NguyenTongPhucNguyen/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Sign in</h4>
            <form>
                <a href="#" class="btn btn-facebook btn-block mb-2"> <i class="fab fa-facebook-f"></i> &nbsp  Sign in with Facebook</a>
                <a href="#" class="btn btn-google btn-block mb-4"> <i class="fab fa-google"></i> &nbsp  Sign in with Google</a>
                <div class="form-group">
                    <input name="" class="form-control" placeholder="Username" type="text">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input name="" class="form-control" placeholder="Password" type="password">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <a href="#" class="float-right">Forgot password?</a>
                    <label class="float-left custom-control custom-checkbox"> <input type="checkbox" class="custom-control-input" checked=""> <div class="custom-control-label"> Remember </div> </label>
                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

NguyenTongPhucNguyen/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="~/Content/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/Scripts/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/Scripts/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="fonts/css/fontawesome/~/Content/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/Content/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/Scripts/js/script.js" type="text/javascript"></script>
    
</head>
<body>

    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="http://bootstrap-ecommerce.com" class="brand-wrap">
                            <img class="logo" src="~/Content/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">All type</option>
                                    <option value="codex">Special</option>
                                    <option value="comments">Only best</option>
                                    <option value="content">Latest</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Search">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                        
                                        <span class="notify">3</span>
                                    </div>
                                    <small> @Html.ActionLink("Đăng nhập", "Login", "Login", new { }, null )</small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                        <span class="notify">1</span>
                                    </div>
                                    <small> @Html.ActionLink("Đăng ký", "Register", "Register", new { }, null ) </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store"></i>
                                    </div>
                                    <small > @Html.ActionLink("Giỏ hàng", "Cart", "Cart", new { }, null) </small>
                                </a>
                           
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-bars text-muted mr-2"></i> Categories </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Machinery</a>
                                <a class="dropdown-item" href="#">Electronics</a>
                                <a class="dropdown-item" href="#">Home textile</a>
                                <a class="dropdown-item" href="#">Home and kitchen</a>
                                <a class="dropdown-item" href="#">Service and equipment</a>
                                <a class="dropdown-item" href="#">Healthcare items</a>
                                <a class="dropdown-item" href="#">Toys and Hobbies</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a @Html.ActionLink("Tất cả danh mục", "Category", "Category", new { }, null)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" @Html.ActionLink("Trang chủ", "Index", "Home", new { }, null)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sell with us</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Demo pages</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="page-index.html">Main</a>
                                <a class="dropdown-item" href="page-category.html">All category</a>
                                <a class="dropdown-item" href="page-listing-large.html">Listing list</a>
                                <a class="dropdown-item" href="page-listing-grid.html">Listing grid</a>
                                <a class="dropdown-item" href="page-shopping-cart.html">Shopping cart</a>
                                <a class="dropdown-item" href="page-detail-product.html">Item detail</a>
                                <a class="dropdown-item" href="page-content.html">Info content</a>
                                <a class="dropdown-item" href="page-user-login.html">Page login</a>
                                <a class="dropdown-item" href="page-user-register.html">Page register</a>
                                <a class="dropdown-item disabled text-muted" href="#">More components</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Get the app</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">English</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Russian</a>
                                <a class="dropdown-item" href="#">French</a>
                                <a class="dropdown-item" href="#">Spanish</a>
                                <a class="dropdown-item" href="#">Chinese</a>
                            </div>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->
     @RenderBody()

    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Brands</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Adidas</a></li>
                            <li> <a href="#">Puma</a></li>
                            <li> <a href="#">Reebok</a></li>
                            <li> <a href="#">Nike</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Company</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">About us</a></li>
                            <li> <a href="#">Career</a></li>
                            <li> <a href="#">Find a store</a></li>
                            <li> <a href="#">Rules and terms</a></li>
                            <li> <a href="#">Sitemap</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Help</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Contact us</a></li>
                            <li> <a href="#">Money refund</a></li>
                            <li> <a href="#">Order status</a></li>
                            <li> <a href="#">Shipping info</a></li>
                            <li> <a href="#">Open dispute</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Account</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> User Login </a></li>
                            <li> <a href="#"> User register </a></li>
                            <li> <a href="#"> Account Setting </a></li>
                            <li> <a href="#"> My Orders </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Social</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
                <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>
    <!-- ========================= FOOTER END // ========================= -->



</body>
</html>